apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  selector:
    app: bff
  ports:
  - protocol: TCP
    port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
  labels:
    app: bff
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: sabbox/bff:7
        ports:
        - containerPort: 8081
        env:
        - name: JOKE_GENERATOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: jokeGeneratorService